name: 'Setup DBT Environment'
description: 'Install DBT, create profiles.yml, and install dependencies'

inputs:
  dbt-profile-content:
    description: 'DBT Profile YAML Content'
    required: true
  dbt-version:
    description: 'DBT SQL Server version'
    required: false
    default: '1.8.5'
  python-version:
    description: 'Python version'
    required: false
    default: '3.9'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install DBT
      shell: bash
      run: |
        echo "📦 Installing DBT..."
        pip install dbt-sqlserver==${{ inputs.dbt-version }} dbt-fabric

    - name: Create profiles.yml
      shell: bash
      run: |
        cat <<EOF > dbt/profiles.yml
        ${{ inputs.dbt-profile-content }}
        EOF

    - name: Install DBT dependencies
      shell: bash
      run: |
        cd dbt
        echo "📦 Installing DBT packages..."
        dbt deps --profiles-dir .
        echo "✅ DBT dependencies installed"
