name: 'Run DBT Workflow'
description: 'Complete DBT workflow: validate, run models, and test'

inputs:
  target:
    description: 'DBT target environment (dev, prod)'
    required: true
  run-models:
    description: 'Whether to run DBT models'
    required: false
    default: 'true'
  run-tests:
    description: 'Whether to run DBT tests'
    required: false
    default: 'true'
  generate-docs:
    description: 'Whether to generate DBT documentation'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Validate DBT project
      shell: bash
      run: |
        cd dbt
        echo "ðŸ” Validating DBT project structure..."
        dbt debug --profiles-dir .
        echo "âœ… DBT project validation passed"

    - name: Compile DBT models
      shell: bash
      run: |
        cd dbt
        echo "ðŸ”„ Compiling DBT models..."
        dbt compile --profiles-dir .
        echo "âœ… DBT models compiled successfully"

    - name: Run DBT models
      if: inputs.run-models == 'true'
      shell: bash
      run: |
        cd dbt
        echo "ðŸš€ Running DBT models for ${{ inputs.target }} environment..."
        dbt run --profiles-dir . --target ${{ inputs.target }} 2>&1 | tee dbt_run.log
        echo "âœ… DBT models executed successfully"

    - name: Run DBT tests
      if: inputs.run-tests == 'true'
      shell: bash
      run: |
        cd dbt
        echo "ðŸ§ª Running data quality tests..."
        dbt test --profiles-dir . --target ${{ inputs.target }} 2>&1 | tee dbt_test.log
        echo "âœ… Data quality tests passed"

    - name: Generate DBT documentation
      if: inputs.generate-docs == 'true'
      shell: bash
      run: |
        cd dbt
        echo "ðŸ“š Generating DBT documentation..."
        dbt docs generate --profiles-dir . --target ${{ inputs.target }}
        echo "âœ… Documentation generated"
